### ISSUE TITLE
Reading the tree

### ISSUE THREAD

**Issue by miracle2k** [ITCase/sqlalchemy_mptt#39]
Maybe I misunderstand, but the only method that I see for actually reading the tree, ``BaseNestedSets.get_tree``, doesn't actually use the MPTT information, but simply executes a lot of queries. 

I'd love to see some helpers for actually querying the tree.

**Comment by uralbash** [comment]
Yes, you're right, this function uses recursion, which creates a lot of queries to the database, shame on me. I'll try to fix it in the next version.

**Comment by uralbash** [comment]
Well, I fixed function ``get_tree``. Now it run only one query to the database and work faster. Please check it out from master branch. If everything is OK, then I close the task.

**Comment by miracle2k** [comment]
That was quick, very cool. Thanks a lot!

**Comment by uralbash** [comment]
Fine, then I close this task. In the future, it will be in 0.1.1 version on PyPi. Thanks for response.
